Composer require civicrm_entity ~3.0
osuosl/snowdrift-civicrm pull request #250
Opened 2023-05-11 16:47 UTC by Justin-Fernbaugh

2023-05-11 20:52 UTC, ramereth requested changes

2023-05-11 20:52 UTC, ramereth commented on composer.json
> +        "drupal/civicrm_entity": "^3.0'",
Try using `~` instead. Also, you need to update the `compose.lock` (see README.md)

2023-05-12 17:48 UTC, Justin-Fernbaugh commented on composer.json
> +        "drupal/civicrm_entity": "^3.0'",
Just pushed those changes

2023-05-15 18:24 UTC, ramereth commented
@Justin-Fernbaugh can I assume this PR shouldn't be merged until this [PR](https://github.com/osuosl-cookbooks/proj-snowdrift/pull/103) is merged as well?

2023-05-15 18:32 UTC, Justin-Fernbaugh commented
> @Justin-Fernbaugh can I assume this PR shouldn't be merged until this [PR](https://github.com/osuosl-cookbooks/proj-snowdrift/pull/103) is merged as well?

I don't believe merging this PR first would produce any errors but yes, they should probably be merged together.

2023-05-16 18:35 UTC, ramereth approved these changes

2023-05-16 18:49 UTC, Justin-Fernbaugh commented
!bump patch ~

2023-05-16 18:51 UTC, ramereth commented
@Justin-Fernbaugh you can just merge this :)

2023-05-16 18:51 UTC, merged